# Generated by Django 3.0.1 on 2019-12-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191226_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='doc_identificacao',
        ),
    ]
